replicaCount: 3

connectors:
# in alertmanager, this will be used as http://prometheus-msteams:2000/kubernetes-monitoring
- kubernetes-monitoring: https://xxxxx.webhook.office.com/webhookb2/96f843e5-16d9-44fb-8a11-d3c7da4880c4@b00367e2-193a-4f48-94de-7245d45c0947/IncomingWebhook/439f6e0a74824e6c9cff3758adc68170/1d39c3f8-0a70-4b38-9133-351cf46c3570
#- foo: https://outlook.office.com/webhook/xxxx/xxxx

metrics:
  serviceMonitor:
    enabled: true
    scrapeInterval: 30s